[main]
title = "Калькулятор FAST-CALC"
input_placeholder = "Введите выражение..."

[main.tabs]
calculator = "Калькулятор"
help = "Помощь"
about = "История"

[history]
empty = "История пуста."
entry_prefix = "> "

[text_screen]
empty = "Нет строк"
