[main]
title = "FAST-CALC"
input_placeholder = "Enter an expression..."

[main.tabs]
calculator = "Calculator"
help = "Help"
about = "History"

[history]
empty = "History is empty."
entry_prefix = "> "

[text_screen]
empty = "No lines"
